"""add_saas_platform_fields

Revision ID: bdc2529576a3
Revises: f1a2b3c4d5e6
Create Date: 2026-03-24 12:20:31.372237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc2529576a3'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invitations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_invitations_token'), 'org_invitations', ['token'], unique=True)
    op.create_table('org_usage',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('total_leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_projects', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.add_column('organizations', sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('subscription_status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'SUSPENDED', name='subscriptionstatus'), server_default='TRIAL', nullable=False))
    op.add_column('organizations', sa.Column('max_users', sa.Integer(), server_default='3', nullable=False))
    op.add_column('organizations', sa.Column('max_projects', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_projects')
    op.drop_column('organizations', 'max_users')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'trial_expires_at')
    op.drop_table('org_usage')
    op.drop_index(op.f('ix_org_invitations_token'), table_name='org_invitations')
    op.drop_table('org_invitations')
    # ### end Alembic commands ###
