"""add_sprint_quantity_and_completion_fields

Revision ID: cd7b0839f5eb
Revises: b4c7d2e8f103
Create Date: 2026-03-20 06:10:17.688273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cd7b0839f5eb"
down_revision: Union[str, None] = "b4c7d2e8f103"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_items_org_category", table_name="items")
    op.drop_index("ix_leads_org_status", table_name="leads")
    op.drop_index("ix_projects_org_status", table_name="projects")
    op.add_column("sprints", sa.Column("planned_quantity", sa.Float(), nullable=True))
    op.add_column("sprints", sa.Column("executed_quantity", sa.Float(), nullable=True))
    op.add_column(
        "sprints", sa.Column("quantity_unit", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "sprints", sa.Column("completion_percentage", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sprints", "completion_percentage")
    op.drop_column("sprints", "quantity_unit")
    op.drop_column("sprints", "executed_quantity")
    op.drop_column("sprints", "planned_quantity")
    op.create_index(
        "ix_projects_org_status", "projects", ["org_id", "status"], unique=False
    )
    op.create_index("ix_leads_org_status", "leads", ["org_id", "status"], unique=False)
    op.create_index(
        "ix_items_org_category", "items", ["org_id", "category"], unique=False
    )
    # ### end Alembic commands ###
